/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1AzureFilePersistentVolumeSource : AzureFile represents an Azure File Service mount on the host and bind mount to the pod.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1AzureFilePersistentVolumeSource {
    /// readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    /// secretName is the name of secret that contains Azure Storage Account Name and Key
    #[serde(rename = "secretName")]
    pub secret_name: String,
    /// secretNamespace is the namespace of the secret that contains Azure Storage Account Name and Key default is the same as the Pod
    #[serde(rename = "secretNamespace", skip_serializing_if = "Option::is_none")]
    pub secret_namespace: Option<String>,
    /// shareName is the azure Share Name
    #[serde(rename = "shareName")]
    pub share_name: String,
}

impl V1AzureFilePersistentVolumeSource {
    /// AzureFile represents an Azure File Service mount on the host and bind mount to the pod.
    pub fn new(secret_name: String, share_name: String) -> V1AzureFilePersistentVolumeSource {
        V1AzureFilePersistentVolumeSource {
            read_only: None,
            secret_name,
            secret_namespace: None,
            share_name,
        }
    }
}


