/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1ContainerUser : ContainerUser represents user identity information



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1ContainerUser {
    #[serde(rename = "linux", skip_serializing_if = "Option::is_none")]
    pub linux: Option<Box<crate::models::V1LinuxContainerUser>>,
}

impl V1ContainerUser {
    /// ContainerUser represents user identity information
    pub fn new() -> V1ContainerUser {
        V1ContainerUser {
            linux: None,
        }
    }
}


