/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1ConfigMapKeySelector : Selects a key from a ConfigMap.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1ConfigMapKeySelector {
    /// The key to select.
    #[serde(rename = "key")]
    pub key: String,
    /// Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Specify whether the ConfigMap or its key must be defined
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

impl V1ConfigMapKeySelector {
    /// Selects a key from a ConfigMap.
    pub fn new(key: String) -> V1ConfigMapKeySelector {
        V1ConfigMapKeySelector {
            key,
            name: None,
            optional: None,
        }
    }
}


