/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1CrossVersionObjectReference : CrossVersionObjectReference contains enough information to let you identify the referred resource.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1CrossVersionObjectReference {
    /// apiVersion is the API version of the referent
    #[serde(rename = "apiVersion", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    /// kind is the kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "kind")]
    pub kind: String,
    /// name is the name of the referent; More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(rename = "name")]
    pub name: String,
}

impl V1CrossVersionObjectReference {
    /// CrossVersionObjectReference contains enough information to let you identify the referred resource.
    pub fn new(kind: String, name: String) -> V1CrossVersionObjectReference {
        V1CrossVersionObjectReference {
            api_version: None,
            kind,
            name,
        }
    }
}


