/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1ContainerResizePolicy : ContainerResizePolicy represents resource resize policy for the container.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1ContainerResizePolicy {
    /// Name of the resource to which this resource resize policy applies. Supported values: cpu, memory.
    #[serde(rename = "resourceName")]
    pub resource_name: String,
    /// Restart policy to apply when specified resource is resized. If not specified, it defaults to NotRequired.
    #[serde(rename = "restartPolicy")]
    pub restart_policy: String,
}

impl V1ContainerResizePolicy {
    /// ContainerResizePolicy represents resource resize policy for the container.
    pub fn new(resource_name: String, restart_policy: String) -> V1ContainerResizePolicy {
        V1ContainerResizePolicy {
            resource_name,
            restart_policy,
        }
    }
}


