/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1EnvVar : EnvVar represents an environment variable present in a Container.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1EnvVar {
    /// Name of the environment variable. Must be a C_IDENTIFIER.
    #[serde(rename = "name")]
    pub name: String,
    /// Variable references $(VAR_NAME) are expanded using the previously defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to \"\".
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "valueFrom", skip_serializing_if = "Option::is_none")]
    pub value_from: Option<Box<crate::models::V1EnvVarSource>>,
}

impl V1EnvVar {
    /// EnvVar represents an environment variable present in a Container.
    pub fn new(name: String) -> V1EnvVar {
        V1EnvVar {
            name,
            value: None,
            value_from: None,
        }
    }
}


