/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1FieldSelectorRequirement : FieldSelectorRequirement is a selector that contains values, a key, and an operator that relates the key and values.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1FieldSelectorRequirement {
    /// key is the field selector key that the requirement applies to.
    #[serde(rename = "key")]
    pub key: String,
    /// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. The list of operators may grow in the future.
    #[serde(rename = "operator")]
    pub operator: String,
    /// values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

impl V1FieldSelectorRequirement {
    /// FieldSelectorRequirement is a selector that contains values, a key, and an operator that relates the key and values.
    pub fn new(key: String, operator: String) -> V1FieldSelectorRequirement {
        V1FieldSelectorRequirement {
            key,
            operator,
            values: None,
        }
    }
}


