/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1HostIp : HostIP represents a single IP address allocated to the host.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1HostIp {
    /// IP is the IP address assigned to the host
    #[serde(rename = "ip")]
    pub ip: String,
}

impl V1HostIp {
    /// HostIP represents a single IP address allocated to the host.
    pub fn new(ip: String) -> V1HostIp {
        V1HostIp {
            ip,
        }
    }
}


