/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1HttpHeader : HTTPHeader describes a custom header to be used in HTTP probes



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1HttpHeader {
    /// The header field name. This will be canonicalized upon output, so case-variant names will be understood as the same header.
    #[serde(rename = "name")]
    pub name: String,
    /// The header field value
    #[serde(rename = "value")]
    pub value: String,
}

impl V1HttpHeader {
    /// HTTPHeader describes a custom header to be used in HTTP probes
    pub fn new(name: String, value: String) -> V1HttpHeader {
        V1HttpHeader {
            name,
            value,
        }
    }
}


