/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1HorizontalPodAutoscalerStatus : current status of a horizontal pod autoscaler



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1HorizontalPodAutoscalerStatus {
    /// currentCPUUtilizationPercentage is the current average CPU utilization over all pods, represented as a percentage of requested CPU, e.g. 70 means that an average pod is using now 70% of its requested CPU.
    #[serde(rename = "currentCPUUtilizationPercentage", skip_serializing_if = "Option::is_none")]
    pub current_cpu_utilization_percentage: Option<i32>,
    /// currentReplicas is the current number of replicas of pods managed by this autoscaler.
    #[serde(rename = "currentReplicas")]
    pub current_replicas: i32,
    /// desiredReplicas is the  desired number of replicas of pods managed by this autoscaler.
    #[serde(rename = "desiredReplicas")]
    pub desired_replicas: i32,
    /// lastScaleTime is the last time the HorizontalPodAutoscaler scaled the number of pods; used by the autoscaler to control how often the number of pods is changed.
    #[serde(rename = "lastScaleTime", skip_serializing_if = "Option::is_none")]
    pub last_scale_time: Option<String>,
    /// observedGeneration is the most recent generation observed by this autoscaler.
    #[serde(rename = "observedGeneration", skip_serializing_if = "Option::is_none")]
    pub observed_generation: Option<i64>,
}

impl V1HorizontalPodAutoscalerStatus {
    /// current status of a horizontal pod autoscaler
    pub fn new(current_replicas: i32, desired_replicas: i32) -> V1HorizontalPodAutoscalerStatus {
        V1HorizontalPodAutoscalerStatus {
            current_cpu_utilization_percentage: None,
            current_replicas,
            desired_replicas,
            last_scale_time: None,
            observed_generation: None,
        }
    }
}


