/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1IngressLoadBalancerStatus : IngressLoadBalancerStatus represents the status of a load-balancer.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1IngressLoadBalancerStatus {
    /// ingress is a list containing ingress points for the load-balancer.
    #[serde(rename = "ingress", skip_serializing_if = "Option::is_none")]
    pub ingress: Option<Vec<crate::models::V1IngressLoadBalancerIngress>>,
}

impl V1IngressLoadBalancerStatus {
    /// IngressLoadBalancerStatus represents the status of a load-balancer.
    pub fn new() -> V1IngressLoadBalancerStatus {
        V1IngressLoadBalancerStatus {
            ingress: None,
        }
    }
}


