/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1IngressLoadBalancerIngress : IngressLoadBalancerIngress represents the status of a load-balancer ingress point.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1IngressLoadBalancerIngress {
    /// hostname is set for load-balancer ingress points that are DNS based.
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    /// ip is set for load-balancer ingress points that are IP based.
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    /// ports provides information about the ports exposed by this LoadBalancer.
    #[serde(rename = "ports", skip_serializing_if = "Option::is_none")]
    pub ports: Option<Vec<crate::models::V1IngressPortStatus>>,
}

impl V1IngressLoadBalancerIngress {
    /// IngressLoadBalancerIngress represents the status of a load-balancer ingress point.
    pub fn new() -> V1IngressLoadBalancerIngress {
        V1IngressLoadBalancerIngress {
            hostname: None,
            ip: None,
            ports: None,
        }
    }
}


