/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1LinuxContainerUser : LinuxContainerUser represents user identity information in Linux containers



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1LinuxContainerUser {
    /// GID is the primary gid initially attached to the first process in the container
    #[serde(rename = "gid")]
    pub gid: i64,
    /// SupplementalGroups are the supplemental groups initially attached to the first process in the container
    #[serde(rename = "supplementalGroups", skip_serializing_if = "Option::is_none")]
    pub supplemental_groups: Option<Vec<i64>>,
    /// UID is the primary uid initially attached to the first process in the container
    #[serde(rename = "uid")]
    pub uid: i64,
}

impl V1LinuxContainerUser {
    /// LinuxContainerUser represents user identity information in Linux containers
    pub fn new(gid: i64, uid: i64) -> V1LinuxContainerUser {
        V1LinuxContainerUser {
            gid,
            supplemental_groups: None,
            uid,
        }
    }
}


