/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1LocalObjectReference : LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1LocalObjectReference {
    /// Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl V1LocalObjectReference {
    /// LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.
    pub fn new() -> V1LocalObjectReference {
        V1LocalObjectReference {
            name: None,
        }
    }
}


