/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1NodeRuntimeHandlerFeatures : NodeRuntimeHandlerFeatures is a set of features implemented by the runtime handler.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1NodeRuntimeHandlerFeatures {
    /// RecursiveReadOnlyMounts is set to true if the runtime handler supports RecursiveReadOnlyMounts.
    #[serde(rename = "recursiveReadOnlyMounts", skip_serializing_if = "Option::is_none")]
    pub recursive_read_only_mounts: Option<bool>,
    /// UserNamespaces is set to true if the runtime handler supports UserNamespaces, including for volumes.
    #[serde(rename = "userNamespaces", skip_serializing_if = "Option::is_none")]
    pub user_namespaces: Option<bool>,
}

impl V1NodeRuntimeHandlerFeatures {
    /// NodeRuntimeHandlerFeatures is a set of features implemented by the runtime handler.
    pub fn new() -> V1NodeRuntimeHandlerFeatures {
        V1NodeRuntimeHandlerFeatures {
            recursive_read_only_mounts: None,
            user_namespaces: None,
        }
    }
}


