/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1NodeConfigSource : NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil. This API is deprecated since 1.22



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1NodeConfigSource {
    #[serde(rename = "configMap", skip_serializing_if = "Option::is_none")]
    pub config_map: Option<Box<crate::models::V1ConfigMapNodeConfigSource>>,
}

impl V1NodeConfigSource {
    /// NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil. This API is deprecated since 1.22
    pub fn new() -> V1NodeConfigSource {
        V1NodeConfigSource {
            config_map: None,
        }
    }
}


