/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1NodeRuntimeHandler : NodeRuntimeHandler is a set of runtime handler information.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1NodeRuntimeHandler {
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Box<crate::models::V1NodeRuntimeHandlerFeatures>>,
    /// Runtime handler name. Empty for the default runtime handler.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl V1NodeRuntimeHandler {
    /// NodeRuntimeHandler is a set of runtime handler information.
    pub fn new() -> V1NodeRuntimeHandler {
        V1NodeRuntimeHandler {
            features: None,
            name: None,
        }
    }
}


