/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1NetworkPolicySpec : NetworkPolicySpec provides the specification of a NetworkPolicy



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1NetworkPolicySpec {
    /// egress is a list of egress rules to be applied to the selected pods. Outgoing traffic is allowed if there are no NetworkPolicies selecting the pod (and cluster policy otherwise allows the traffic), OR if the traffic matches at least one egress rule across all of the NetworkPolicy objects whose podSelector matches the pod. If this field is empty then this NetworkPolicy limits all outgoing traffic (and serves solely to ensure that the pods it selects are isolated by default). This field is beta-level in 1.8
    #[serde(rename = "egress", skip_serializing_if = "Option::is_none")]
    pub egress: Option<Vec<crate::models::V1NetworkPolicyEgressRule>>,
    /// ingress is a list of ingress rules to be applied to the selected pods. Traffic is allowed to a pod if there are no NetworkPolicies selecting the pod (and cluster policy otherwise allows the traffic), OR if the traffic source is the pod's local node, OR if the traffic matches at least one ingress rule across all of the NetworkPolicy objects whose podSelector matches the pod. If this field is empty then this NetworkPolicy does not allow any traffic (and serves solely to ensure that the pods it selects are isolated by default)
    #[serde(rename = "ingress", skip_serializing_if = "Option::is_none")]
    pub ingress: Option<Vec<crate::models::V1NetworkPolicyIngressRule>>,
    #[serde(rename = "podSelector")]
    pub pod_selector: Box<crate::models::V1LabelSelector>,
    /// policyTypes is a list of rule types that the NetworkPolicy relates to. Valid options are [\"Ingress\"], [\"Egress\"], or [\"Ingress\", \"Egress\"]. If this field is not specified, it will default based on the existence of ingress or egress rules; policies that contain an egress section are assumed to affect egress, and all policies (whether or not they contain an ingress section) are assumed to affect ingress. If you want to write an egress-only policy, you must explicitly specify policyTypes [ \"Egress\" ]. Likewise, if you want to write a policy that specifies that no egress is allowed, you must specify a policyTypes value that include \"Egress\" (since such a policy would not include an egress section and would otherwise default to just [ \"Ingress\" ]). This field is beta-level in 1.8
    #[serde(rename = "policyTypes", skip_serializing_if = "Option::is_none")]
    pub policy_types: Option<Vec<String>>,
}

impl V1NetworkPolicySpec {
    /// NetworkPolicySpec provides the specification of a NetworkPolicy
    pub fn new(pod_selector: crate::models::V1LabelSelector) -> V1NetworkPolicySpec {
        V1NetworkPolicySpec {
            egress: None,
            ingress: None,
            pod_selector: Box::new(pod_selector),
            policy_types: None,
        }
    }
}


