/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1PersistentVolumeClaimCondition : PersistentVolumeClaimCondition contains details about state of pvc



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PersistentVolumeClaimCondition {
    /// lastProbeTime is the time we probed the condition.
    #[serde(rename = "lastProbeTime", skip_serializing_if = "Option::is_none")]
    pub last_probe_time: Option<String>,
    /// lastTransitionTime is the time the condition transitioned from one status to another.
    #[serde(rename = "lastTransitionTime", skip_serializing_if = "Option::is_none")]
    pub last_transition_time: Option<String>,
    /// message is the human-readable message indicating details about last transition.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// reason is a unique, this should be a short, machine understandable string that gives the reason for condition's last transition. If it reports \"Resizing\" that means the underlying persistent volume is being resized.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "type")]
    pub _type: String,
}

impl V1PersistentVolumeClaimCondition {
    /// PersistentVolumeClaimCondition contains details about state of pvc
    pub fn new(status: String, _type: String) -> V1PersistentVolumeClaimCondition {
        V1PersistentVolumeClaimCondition {
            last_probe_time: None,
            last_transition_time: None,
            message: None,
            reason: None,
            status,
            _type,
        }
    }
}


