/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1PriorityLevelConfigurationSpec : PriorityLevelConfigurationSpec specifies the configuration of a priority level.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PriorityLevelConfigurationSpec {
    #[serde(rename = "exempt", skip_serializing_if = "Option::is_none")]
    pub exempt: Option<Box<crate::models::V1ExemptPriorityLevelConfiguration>>,
    #[serde(rename = "limited", skip_serializing_if = "Option::is_none")]
    pub limited: Option<Box<crate::models::V1LimitedPriorityLevelConfiguration>>,
    /// `type` indicates whether this priority level is subject to limitation on request execution.  A value of `\"Exempt\"` means that requests of this priority level are not subject to a limit (and thus are never queued) and do not detract from the capacity made available to other priority levels.  A value of `\"Limited\"` means that (a) requests of this priority level _are_ subject to limits and (b) some of the server's limited capacity is made available exclusively to this priority level. Required.
    #[serde(rename = "type")]
    pub _type: String,
}

impl V1PriorityLevelConfigurationSpec {
    /// PriorityLevelConfigurationSpec specifies the configuration of a priority level.
    pub fn new(_type: String) -> V1PriorityLevelConfigurationSpec {
        V1PriorityLevelConfigurationSpec {
            exempt: None,
            limited: None,
            _type,
        }
    }
}


