/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1PodIp : PodIP represents a single IP address allocated to the pod.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PodIp {
    /// IP is the IP address assigned to the pod
    #[serde(rename = "ip")]
    pub ip: String,
}

impl V1PodIp {
    /// PodIP represents a single IP address allocated to the pod.
    pub fn new(ip: String) -> V1PodIp {
        V1PodIp {
            ip,
        }
    }
}


