/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1PodOs : PodOS defines the OS parameters of a pod.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PodOs {
    /// Name is the name of the operating system. The currently supported values are linux and windows. Additional value may be defined in future and can be one of: https://github.com/opencontainers/runtime-spec/blob/master/config.md#platform-specific-configuration Clients should expect to handle additional values and treat unrecognized values in this field as os: null
    #[serde(rename = "name")]
    pub name: String,
}

impl V1PodOs {
    /// PodOS defines the OS parameters of a pod.
    pub fn new(name: String) -> V1PodOs {
        V1PodOs {
            name,
        }
    }
}


