/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1PodFailurePolicy : PodFailurePolicy describes how failed pods influence the backoffLimit.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PodFailurePolicy {
    /// A list of pod failure policy rules. The rules are evaluated in order. Once a rule matches a Pod failure, the remaining of the rules are ignored. When no rule matches the Pod failure, the default handling applies - the counter of pod failures is incremented and it is checked against the backoffLimit. At most 20 elements are allowed.
    #[serde(rename = "rules")]
    pub rules: Vec<crate::models::V1PodFailurePolicyRule>,
}

impl V1PodFailurePolicy {
    /// PodFailurePolicy describes how failed pods influence the backoffLimit.
    pub fn new(rules: Vec<crate::models::V1PodFailurePolicyRule>) -> V1PodFailurePolicy {
        V1PodFailurePolicy {
            rules,
        }
    }
}


