/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1PodFailurePolicyOnPodConditionsPattern : PodFailurePolicyOnPodConditionsPattern describes a pattern for matching an actual pod condition type.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PodFailurePolicyOnPodConditionsPattern {
    /// Specifies the required Pod condition status. To match a pod condition it is required that the specified status equals the pod condition status. Defaults to True.
    #[serde(rename = "status")]
    pub status: String,
    /// Specifies the required Pod condition type. To match a pod condition it is required that specified type equals the pod condition type.
    #[serde(rename = "type")]
    pub _type: String,
}

impl V1PodFailurePolicyOnPodConditionsPattern {
    /// PodFailurePolicyOnPodConditionsPattern describes a pattern for matching an actual pod condition type.
    pub fn new(status: String, _type: String) -> V1PodFailurePolicyOnPodConditionsPattern {
        V1PodFailurePolicyOnPodConditionsPattern {
            status,
            _type,
        }
    }
}


