/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1ProjectedVolumeSource : Represents a projected volume source



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1ProjectedVolumeSource {
    /// defaultMode are the mode bits used to set permissions on created files by default. Must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
    #[serde(rename = "defaultMode", skip_serializing_if = "Option::is_none")]
    pub default_mode: Option<i32>,
    /// sources is the list of volume projections. Each entry in this list handles one source.
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<crate::models::V1VolumeProjection>>,
}

impl V1ProjectedVolumeSource {
    /// Represents a projected volume source
    pub fn new() -> V1ProjectedVolumeSource {
        V1ProjectedVolumeSource {
            default_mode: None,
            sources: None,
        }
    }
}


