/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1ResourceStatus {
    /// Name of the resource. Must be unique within the pod and match one of the resources from the pod spec.
    #[serde(rename = "name")]
    pub name: String,
    /// List of unique Resources health. Each element in the list contains an unique resource ID and resource health. At a minimum, ResourceID must uniquely identify the Resource allocated to the Pod on the Node for the lifetime of a Pod. See ResourceID type for it's definition.
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Vec<crate::models::V1ResourceHealth>>,
}

impl V1ResourceStatus {
    pub fn new(name: String) -> V1ResourceStatus {
        V1ResourceStatus {
            name,
            resources: None,
        }
    }
}


