/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1ResourceClaim : ResourceClaim references one entry in PodSpec.ResourceClaims.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1ResourceClaim {
    /// Name must match the name of one entry in pod.spec.resourceClaims of the Pod where this field is used. It makes that resource available inside a container.
    #[serde(rename = "name")]
    pub name: String,
    /// Request is the name chosen for a request in the referenced claim. If empty, everything from the claim is made available, otherwise only the result of this request.
    #[serde(rename = "request", skip_serializing_if = "Option::is_none")]
    pub request: Option<String>,
}

impl V1ResourceClaim {
    /// ResourceClaim references one entry in PodSpec.ResourceClaims.
    pub fn new(name: String) -> V1ResourceClaim {
        V1ResourceClaim {
            name,
            request: None,
        }
    }
}


