/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1SelfSubjectRulesReviewSpec : SelfSubjectRulesReviewSpec defines the specification for SelfSubjectRulesReview.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1SelfSubjectRulesReviewSpec {
    /// Namespace to evaluate rules for. Required.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

impl V1SelfSubjectRulesReviewSpec {
    /// SelfSubjectRulesReviewSpec defines the specification for SelfSubjectRulesReview.
    pub fn new() -> V1SelfSubjectRulesReviewSpec {
        V1SelfSubjectRulesReviewSpec {
            namespace: None,
        }
    }
}


