/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1SelectableField : SelectableField specifies the JSON path of a field that may be used with field selectors.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1SelectableField {
    /// jsonPath is a simple JSON path which is evaluated against each custom resource to produce a field selector value. Only JSON paths without the array notation are allowed. Must point to a field of type string, boolean or integer. Types with enum values and strings with formats are allowed. If jsonPath refers to absent field in a resource, the jsonPath evaluates to an empty string. Must not point to metdata fields. Required.
    #[serde(rename = "jsonPath")]
    pub json_path: String,
}

impl V1SelectableField {
    /// SelectableField specifies the JSON path of a field that may be used with field selectors.
    pub fn new(json_path: String) -> V1SelectableField {
        V1SelectableField {
            json_path,
        }
    }
}


