/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1SecretKeySelector : SecretKeySelector selects a key of a Secret.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1SecretKeySelector {
    /// The key of the secret to select from.  Must be a valid secret key.
    #[serde(rename = "key")]
    pub key: String,
    /// Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Specify whether the Secret or its key must be defined
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

impl V1SecretKeySelector {
    /// SecretKeySelector selects a key of a Secret.
    pub fn new(key: String) -> V1SecretKeySelector {
        V1SecretKeySelector {
            key,
            name: None,
            optional: None,
        }
    }
}


