/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1StatefulSetOrdinals : StatefulSetOrdinals describes the policy used for replica ordinal assignment in this StatefulSet.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1StatefulSetOrdinals {
    /// start is the number representing the first replica's index. It may be used to number replicas from an alternate index (eg: 1-indexed) over the default 0-indexed names, or to orchestrate progressive movement of replicas from one StatefulSet to another. If set, replica indices will be in the range:   [.spec.ordinals.start, .spec.ordinals.start + .spec.replicas). If unset, defaults to 0. Replica indices will be in the range:   [0, .spec.replicas).
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i32>,
}

impl V1StatefulSetOrdinals {
    /// StatefulSetOrdinals describes the policy used for replica ordinal assignment in this StatefulSet.
    pub fn new() -> V1StatefulSetOrdinals {
        V1StatefulSetOrdinals {
            start: None,
        }
    }
}


