/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1StatefulSetPersistentVolumeClaimRetentionPolicy : StatefulSetPersistentVolumeClaimRetentionPolicy describes the policy used for PVCs created from the StatefulSet VolumeClaimTemplates.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1StatefulSetPersistentVolumeClaimRetentionPolicy {
    /// WhenDeleted specifies what happens to PVCs created from StatefulSet VolumeClaimTemplates when the StatefulSet is deleted. The default policy of `Retain` causes PVCs to not be affected by StatefulSet deletion. The `Delete` policy causes those PVCs to be deleted.
    #[serde(rename = "whenDeleted", skip_serializing_if = "Option::is_none")]
    pub when_deleted: Option<String>,
    /// WhenScaled specifies what happens to PVCs created from StatefulSet VolumeClaimTemplates when the StatefulSet is scaled down. The default policy of `Retain` causes PVCs to not be affected by a scaledown. The `Delete` policy causes the associated PVCs for any excess pods above the replica count to be deleted.
    #[serde(rename = "whenScaled", skip_serializing_if = "Option::is_none")]
    pub when_scaled: Option<String>,
}

impl V1StatefulSetPersistentVolumeClaimRetentionPolicy {
    /// StatefulSetPersistentVolumeClaimRetentionPolicy describes the policy used for PVCs created from the StatefulSet VolumeClaimTemplates.
    pub fn new() -> V1StatefulSetPersistentVolumeClaimRetentionPolicy {
        V1StatefulSetPersistentVolumeClaimRetentionPolicy {
            when_deleted: None,
            when_scaled: None,
        }
    }
}


