/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1SuccessPolicy : SuccessPolicy describes when a Job can be declared as succeeded based on the success of some indexes.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1SuccessPolicy {
    /// rules represents the list of alternative rules for the declaring the Jobs as successful before `.status.succeeded >= .spec.completions`. Once any of the rules are met, the \"SucceededCriteriaMet\" condition is added, and the lingering pods are removed. The terminal state for such a Job has the \"Complete\" condition. Additionally, these rules are evaluated in order; Once the Job meets one of the rules, other rules are ignored. At most 20 elements are allowed.
    #[serde(rename = "rules")]
    pub rules: Vec<crate::models::V1SuccessPolicyRule>,
}

impl V1SuccessPolicy {
    /// SuccessPolicy describes when a Job can be declared as succeeded based on the success of some indexes.
    pub fn new(rules: Vec<crate::models::V1SuccessPolicyRule>) -> V1SuccessPolicy {
        V1SuccessPolicy {
            rules,
        }
    }
}


