/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1UncountedTerminatedPods : UncountedTerminatedPods holds UIDs of Pods that have terminated but haven't been accounted in Job status counters.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1UncountedTerminatedPods {
    /// failed holds UIDs of failed Pods.
    #[serde(rename = "failed", skip_serializing_if = "Option::is_none")]
    pub failed: Option<Vec<String>>,
    /// succeeded holds UIDs of succeeded Pods.
    #[serde(rename = "succeeded", skip_serializing_if = "Option::is_none")]
    pub succeeded: Option<Vec<String>>,
}

impl V1UncountedTerminatedPods {
    /// UncountedTerminatedPods holds UIDs of Pods that have terminated but haven't been accounted in Job status counters.
    pub fn new() -> V1UncountedTerminatedPods {
        V1UncountedTerminatedPods {
            failed: None,
            succeeded: None,
        }
    }
}


