/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1VolumeAttachmentStatus : VolumeAttachmentStatus is the status of a VolumeAttachment request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1VolumeAttachmentStatus {
    #[serde(rename = "attachError", skip_serializing_if = "Option::is_none")]
    pub attach_error: Option<Box<crate::models::V1VolumeError>>,
    /// attached indicates the volume is successfully attached. This field must only be set by the entity completing the attach operation, i.e. the external-attacher.
    #[serde(rename = "attached")]
    pub attached: bool,
    /// attachmentMetadata is populated with any information returned by the attach operation, upon successful attach, that must be passed into subsequent WaitForAttach or Mount calls. This field must only be set by the entity completing the attach operation, i.e. the external-attacher.
    #[serde(rename = "attachmentMetadata", skip_serializing_if = "Option::is_none")]
    pub attachment_metadata: Option<::std::collections::HashMap<String, String>>,
    #[serde(rename = "detachError", skip_serializing_if = "Option::is_none")]
    pub detach_error: Option<Box<crate::models::V1VolumeError>>,
}

impl V1VolumeAttachmentStatus {
    /// VolumeAttachmentStatus is the status of a VolumeAttachment request.
    pub fn new(attached: bool) -> V1VolumeAttachmentStatus {
        V1VolumeAttachmentStatus {
            attach_error: None,
            attached,
            attachment_metadata: None,
            detach_error: None,
        }
    }
}


