/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1Variable : Variable is the definition of a variable that is used for composition. A variable is defined as a named expression.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1Variable {
    /// Expression is the expression that will be evaluated as the value of the variable. The CEL expression has access to the same identifiers as the CEL expressions in Validation.
    #[serde(rename = "expression")]
    pub expression: String,
    /// Name is the name of the variable. The name must be a valid CEL identifier and unique among all variables. The variable can be accessed in other expressions through `variables` For example, if name is \"foo\", the variable will be available as `variables.foo`
    #[serde(rename = "name")]
    pub name: String,
}

impl V1Variable {
    /// Variable is the definition of a variable that is used for composition. A variable is defined as a named expression.
    pub fn new(expression: String, name: String) -> V1Variable {
        V1Variable {
            expression,
            name,
        }
    }
}


