/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1VolumeMountStatus : VolumeMountStatus shows status of volume mounts.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1VolumeMountStatus {
    /// MountPath corresponds to the original VolumeMount.
    #[serde(rename = "mountPath")]
    pub mount_path: String,
    /// Name corresponds to the name of the original VolumeMount.
    #[serde(rename = "name")]
    pub name: String,
    /// ReadOnly corresponds to the original VolumeMount.
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    /// RecursiveReadOnly must be set to Disabled, Enabled, or unspecified (for non-readonly mounts). An IfPossible value in the original VolumeMount must be translated to Disabled or Enabled, depending on the mount result.
    #[serde(rename = "recursiveReadOnly", skip_serializing_if = "Option::is_none")]
    pub recursive_read_only: Option<String>,
}

impl V1VolumeMountStatus {
    /// VolumeMountStatus shows status of volume mounts.
    pub fn new(mount_path: String, name: String) -> V1VolumeMountStatus {
        V1VolumeMountStatus {
            mount_path,
            name,
            read_only: None,
            recursive_read_only: None,
        }
    }
}


