/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1VolumeProjection : Projection that may be projected along with other supported volume types. Exactly one of these fields must be set.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1VolumeProjection {
    #[serde(rename = "clusterTrustBundle", skip_serializing_if = "Option::is_none")]
    pub cluster_trust_bundle: Option<Box<crate::models::V1ClusterTrustBundleProjection>>,
    #[serde(rename = "configMap", skip_serializing_if = "Option::is_none")]
    pub config_map: Option<Box<crate::models::V1ConfigMapProjection>>,
    #[serde(rename = "downwardAPI", skip_serializing_if = "Option::is_none")]
    pub downward_api: Option<Box<crate::models::V1DownwardApiProjection>>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<Box<crate::models::V1SecretProjection>>,
    #[serde(rename = "serviceAccountToken", skip_serializing_if = "Option::is_none")]
    pub service_account_token: Option<Box<crate::models::V1ServiceAccountTokenProjection>>,
}

impl V1VolumeProjection {
    /// Projection that may be projected along with other supported volume types. Exactly one of these fields must be set.
    pub fn new() -> V1VolumeProjection {
        V1VolumeProjection {
            cluster_trust_bundle: None,
            config_map: None,
            downward_api: None,
            secret: None,
            service_account_token: None,
        }
    }
}


