/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha1ValidatingAdmissionPolicyStatus : ValidatingAdmissionPolicyStatus represents the status of a ValidatingAdmissionPolicy.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha1ValidatingAdmissionPolicyStatus {
    /// The conditions represent the latest available observations of a policy's current state.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::V1Condition>>,
    /// The generation observed by the controller.
    #[serde(rename = "observedGeneration", skip_serializing_if = "Option::is_none")]
    pub observed_generation: Option<i64>,
    #[serde(rename = "typeChecking", skip_serializing_if = "Option::is_none")]
    pub type_checking: Option<Box<crate::models::V1alpha1TypeChecking>>,
}

impl V1alpha1ValidatingAdmissionPolicyStatus {
    /// ValidatingAdmissionPolicyStatus represents the status of a ValidatingAdmissionPolicy.
    pub fn new() -> V1alpha1ValidatingAdmissionPolicyStatus {
        V1alpha1ValidatingAdmissionPolicyStatus {
            conditions: None,
            observed_generation: None,
            type_checking: None,
        }
    }
}


