/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha1MigrationCondition : Describes the state of a migration at a certain point.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha1MigrationCondition {
    /// The last time this condition was updated.
    #[serde(rename = "lastUpdateTime", skip_serializing_if = "Option::is_none")]
    pub last_update_time: Option<String>,
    /// A human readable message indicating details about the transition.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The reason for the condition's last transition.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Status of the condition, one of True, False, Unknown.
    #[serde(rename = "status")]
    pub status: String,
    /// Type of the condition.
    #[serde(rename = "type")]
    pub _type: String,
}

impl V1alpha1MigrationCondition {
    /// Describes the state of a migration at a certain point.
    pub fn new(status: String, _type: String) -> V1alpha1MigrationCondition {
        V1alpha1MigrationCondition {
            last_update_time: None,
            message: None,
            reason: None,
            status,
            _type,
        }
    }
}


