/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha3Device : Device represents one individual hardware instance that can be selected based on its attributes. Besides the name, exactly one field must be set.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha3Device {
    #[serde(rename = "basic", skip_serializing_if = "Option::is_none")]
    pub basic: Option<Box<crate::models::V1alpha3BasicDevice>>,
    /// Name is unique identifier among all devices managed by the driver in the pool. It must be a DNS label.
    #[serde(rename = "name")]
    pub name: String,
}

impl V1alpha3Device {
    /// Device represents one individual hardware instance that can be selected based on its attributes. Besides the name, exactly one field must be set.
    pub fn new(name: String) -> V1alpha3Device {
        V1alpha3Device {
            basic: None,
            name,
        }
    }
}


