/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha3PodSchedulingContextStatus : PodSchedulingContextStatus describes where resources for the Pod can be allocated.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha3PodSchedulingContextStatus {
    /// ResourceClaims describes resource availability for each pod.spec.resourceClaim entry where the corresponding ResourceClaim uses \"WaitForFirstConsumer\" allocation mode.
    #[serde(rename = "resourceClaims", skip_serializing_if = "Option::is_none")]
    pub resource_claims: Option<Vec<crate::models::V1alpha3ResourceClaimSchedulingStatus>>,
}

impl V1alpha3PodSchedulingContextStatus {
    /// PodSchedulingContextStatus describes where resources for the Pod can be allocated.
    pub fn new() -> V1alpha3PodSchedulingContextStatus {
        V1alpha3PodSchedulingContextStatus {
            resource_claims: None,
        }
    }
}


