/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha1SelfSubjectReviewStatus : SelfSubjectReviewStatus is filled by the kube-apiserver and sent back to a user.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha1SelfSubjectReviewStatus {
    #[serde(rename = "userInfo", skip_serializing_if = "Option::is_none")]
    pub user_info: Option<Box<crate::models::V1UserInfo>>,
}

impl V1alpha1SelfSubjectReviewStatus {
    /// SelfSubjectReviewStatus is filled by the kube-apiserver and sent back to a user.
    pub fn new() -> V1alpha1SelfSubjectReviewStatus {
        V1alpha1SelfSubjectReviewStatus {
            user_info: None,
        }
    }
}


