/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha1GroupVersionResource : The names of the group, the version, and the resource.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha1GroupVersionResource {
    /// The name of the group.
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    /// The name of the resource.
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    /// The name of the version.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl V1alpha1GroupVersionResource {
    /// The names of the group, the version, and the resource.
    pub fn new() -> V1alpha1GroupVersionResource {
        V1alpha1GroupVersionResource {
            group: None,
            resource: None,
            version: None,
        }
    }
}


