/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha3DeviceClaimConfiguration : DeviceClaimConfiguration is used for configuration parameters in DeviceClaim.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha3DeviceClaimConfiguration {
    #[serde(rename = "opaque", skip_serializing_if = "Option::is_none")]
    pub opaque: Option<Box<crate::models::V1alpha3OpaqueDeviceConfiguration>>,
    /// Requests lists the names of requests where the configuration applies. If empty, it applies to all requests.
    #[serde(rename = "requests", skip_serializing_if = "Option::is_none")]
    pub requests: Option<Vec<String>>,
}

impl V1alpha3DeviceClaimConfiguration {
    /// DeviceClaimConfiguration is used for configuration parameters in DeviceClaim.
    pub fn new() -> V1alpha3DeviceClaimConfiguration {
        V1alpha3DeviceClaimConfiguration {
            opaque: None,
            requests: None,
        }
    }
}


