/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha3ResourceClaimTemplateSpec : ResourceClaimTemplateSpec contains the metadata and fields for a ResourceClaim.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha3ResourceClaimTemplateSpec {
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::V1ObjectMeta>>,
    #[serde(rename = "spec")]
    pub spec: Box<crate::models::V1alpha3ResourceClaimSpec>,
}

impl V1alpha3ResourceClaimTemplateSpec {
    /// ResourceClaimTemplateSpec contains the metadata and fields for a ResourceClaim.
    pub fn new(spec: crate::models::V1alpha3ResourceClaimSpec) -> V1alpha3ResourceClaimTemplateSpec {
        V1alpha3ResourceClaimTemplateSpec {
            metadata: None,
            spec: Box::new(spec),
        }
    }
}


