/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha1StorageVersionMigrationStatus : Status of the storage version migration.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha1StorageVersionMigrationStatus {
    /// The latest available observations of the migration's current state.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::V1alpha1MigrationCondition>>,
    /// ResourceVersion to compare with the GC cache for performing the migration. This is the current resource version of given group, version and resource when kube-controller-manager first observes this StorageVersionMigration resource.
    #[serde(rename = "resourceVersion", skip_serializing_if = "Option::is_none")]
    pub resource_version: Option<String>,
}

impl V1alpha1StorageVersionMigrationStatus {
    /// Status of the storage version migration.
    pub fn new() -> V1alpha1StorageVersionMigrationStatus {
        V1alpha1StorageVersionMigrationStatus {
            conditions: None,
            resource_version: None,
        }
    }
}


