/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha3DeviceClassConfiguration : DeviceClassConfiguration is used in DeviceClass.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha3DeviceClassConfiguration {
    #[serde(rename = "opaque", skip_serializing_if = "Option::is_none")]
    pub opaque: Option<Box<crate::models::V1alpha3OpaqueDeviceConfiguration>>,
}

impl V1alpha3DeviceClassConfiguration {
    /// DeviceClassConfiguration is used in DeviceClass.
    pub fn new() -> V1alpha3DeviceClassConfiguration {
        V1alpha3DeviceClassConfiguration {
            opaque: None,
        }
    }
}


