/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha1LeaseCandidateSpec : LeaseCandidateSpec is a specification of a Lease.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha1LeaseCandidateSpec {
    /// BinaryVersion is the binary version. It must be in a semver format without leading `v`. This field is required when strategy is \"OldestEmulationVersion\"
    #[serde(rename = "binaryVersion", skip_serializing_if = "Option::is_none")]
    pub binary_version: Option<String>,
    /// EmulationVersion is the emulation version. It must be in a semver format without leading `v`. EmulationVersion must be less than or equal to BinaryVersion. This field is required when strategy is \"OldestEmulationVersion\"
    #[serde(rename = "emulationVersion", skip_serializing_if = "Option::is_none")]
    pub emulation_version: Option<String>,
    /// LeaseName is the name of the lease for which this candidate is contending. This field is immutable.
    #[serde(rename = "leaseName")]
    pub lease_name: String,
    /// PingTime is the last time that the server has requested the LeaseCandidate to renew. It is only done during leader election to check if any LeaseCandidates have become ineligible. When PingTime is updated, the LeaseCandidate will respond by updating RenewTime.
    #[serde(rename = "pingTime", skip_serializing_if = "Option::is_none")]
    pub ping_time: Option<String>,
    /// PreferredStrategies indicates the list of strategies for picking the leader for coordinated leader election. The list is ordered, and the first strategy supersedes all other strategies. The list is used by coordinated leader election to make a decision about the final election strategy. This follows as - If all clients have strategy X as the first element in this list, strategy X will be used. - If a candidate has strategy [X] and another candidate has strategy [Y, X], Y supersedes X and strategy Y   will be used. - If a candidate has strategy [X, Y] and another candidate has strategy [Y, X], this is a user error and leader   election will not operate the Lease until resolved. (Alpha) Using this field requires the CoordinatedLeaderElection feature gate to be enabled.
    #[serde(rename = "preferredStrategies")]
    pub preferred_strategies: Vec<String>,
    /// RenewTime is the time that the LeaseCandidate was last updated. Any time a Lease needs to do leader election, the PingTime field is updated to signal to the LeaseCandidate that they should update the RenewTime. Old LeaseCandidate objects are also garbage collected if it has been hours since the last renew. The PingTime field is updated regularly to prevent garbage collection for still active LeaseCandidates.
    #[serde(rename = "renewTime", skip_serializing_if = "Option::is_none")]
    pub renew_time: Option<String>,
}

impl V1alpha1LeaseCandidateSpec {
    /// LeaseCandidateSpec is a specification of a Lease.
    pub fn new(lease_name: String, preferred_strategies: Vec<String>) -> V1alpha1LeaseCandidateSpec {
        V1alpha1LeaseCandidateSpec {
            binary_version: None,
            emulation_version: None,
            lease_name,
            ping_time: None,
            preferred_strategies,
            renew_time: None,
        }
    }
}


