/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha3ResourceSliceSpec : ResourceSliceSpec contains the information published by the driver in one ResourceSlice.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha3ResourceSliceSpec {
    /// AllNodes indicates that all nodes have access to the resources in the pool.  Exactly one of NodeName, NodeSelector and AllNodes must be set.
    #[serde(rename = "allNodes", skip_serializing_if = "Option::is_none")]
    pub all_nodes: Option<bool>,
    /// Devices lists some or all of the devices in this pool.  Must not have more than 128 entries.
    #[serde(rename = "devices", skip_serializing_if = "Option::is_none")]
    pub devices: Option<Vec<crate::models::V1alpha3Device>>,
    /// Driver identifies the DRA driver providing the capacity information. A field selector can be used to list only ResourceSlice objects with a certain driver name.  Must be a DNS subdomain and should end with a DNS domain owned by the vendor of the driver. This field is immutable.
    #[serde(rename = "driver")]
    pub driver: String,
    /// NodeName identifies the node which provides the resources in this pool. A field selector can be used to list only ResourceSlice objects belonging to a certain node.  This field can be used to limit access from nodes to ResourceSlices with the same node name. It also indicates to autoscalers that adding new nodes of the same type as some old node might also make new resources available.  Exactly one of NodeName, NodeSelector and AllNodes must be set. This field is immutable.
    #[serde(rename = "nodeName", skip_serializing_if = "Option::is_none")]
    pub node_name: Option<String>,
    #[serde(rename = "nodeSelector", skip_serializing_if = "Option::is_none")]
    pub node_selector: Option<Box<crate::models::V1NodeSelector>>,
    #[serde(rename = "pool")]
    pub pool: Box<crate::models::V1alpha3ResourcePool>,
}

impl V1alpha3ResourceSliceSpec {
    /// ResourceSliceSpec contains the information published by the driver in one ResourceSlice.
    pub fn new(driver: String, pool: crate::models::V1alpha3ResourcePool) -> V1alpha3ResourceSliceSpec {
        V1alpha3ResourceSliceSpec {
            all_nodes: None,
            devices: None,
            driver,
            node_name: None,
            node_selector: None,
            pool: Box::new(pool),
        }
    }
}


