/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha3OpaqueDeviceConfiguration : OpaqueDeviceConfiguration contains configuration parameters for a driver in a format defined by the driver vendor.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha3OpaqueDeviceConfiguration {
    /// Driver is used to determine which kubelet plugin needs to be passed these configuration parameters.  An admission policy provided by the driver developer could use this to decide whether it needs to validate them.  Must be a DNS subdomain and should end with a DNS domain owned by the vendor of the driver.
    #[serde(rename = "driver")]
    pub driver: String,
    /// Parameters can contain arbitrary data. It is the responsibility of the driver developer to handle validation and versioning. Typically this includes self-identification and a version (\"kind\" + \"apiVersion\" for Kubernetes types), with conversion between different versions.
    #[serde(rename = "parameters")]
    pub parameters: serde_json::Value,
}

impl V1alpha3OpaqueDeviceConfiguration {
    /// OpaqueDeviceConfiguration contains configuration parameters for a driver in a format defined by the driver vendor.
    pub fn new(driver: String, parameters: serde_json::Value) -> V1alpha3OpaqueDeviceConfiguration {
        V1alpha3OpaqueDeviceConfiguration {
            driver,
            parameters,
        }
    }
}


