/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha3DeviceConstraint : DeviceConstraint must have exactly one field set besides Requests.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha3DeviceConstraint {
    /// MatchAttribute requires that all devices in question have this attribute and that its type and value are the same across those devices.  For example, if you specified \"dra.example.com/numa\" (a hypothetical example!), then only devices in the same NUMA node will be chosen. A device which does not have that attribute will not be chosen. All devices should use a value of the same type for this attribute because that is part of its specification, but if one device doesn't, then it also will not be chosen.  Must include the domain qualifier.
    #[serde(rename = "matchAttribute", skip_serializing_if = "Option::is_none")]
    pub match_attribute: Option<String>,
    /// Requests is a list of the one or more requests in this claim which must co-satisfy this constraint. If a request is fulfilled by multiple devices, then all of the devices must satisfy the constraint. If this is not specified, this constraint applies to all requests in this claim.
    #[serde(rename = "requests", skip_serializing_if = "Option::is_none")]
    pub requests: Option<Vec<String>>,
}

impl V1alpha3DeviceConstraint {
    /// DeviceConstraint must have exactly one field set besides Requests.
    pub fn new() -> V1alpha3DeviceConstraint {
        V1alpha3DeviceConstraint {
            match_attribute: None,
            requests: None,
        }
    }
}


