/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1alpha3DeviceSelector : DeviceSelector must have exactly one field set.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha3DeviceSelector {
    #[serde(rename = "cel", skip_serializing_if = "Option::is_none")]
    pub cel: Option<Box<crate::models::V1alpha3CelDeviceSelector>>,
}

impl V1alpha3DeviceSelector {
    /// DeviceSelector must have exactly one field set.
    pub fn new() -> V1alpha3DeviceSelector {
        V1alpha3DeviceSelector {
            cel: None,
        }
    }
}


