/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta3GroupSubject : GroupSubject holds detailed information for group-kind subject.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta3GroupSubject {
    /// name is the user group that matches, or \"*\" to match all user groups. See https://github.com/kubernetes/apiserver/blob/master/pkg/authentication/user/user.go for some well-known group names. Required.
    #[serde(rename = "name")]
    pub name: String,
}

impl V1beta3GroupSubject {
    /// GroupSubject holds detailed information for group-kind subject.
    pub fn new(name: String) -> V1beta3GroupSubject {
        V1beta3GroupSubject {
            name,
        }
    }
}


