/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta3PriorityLevelConfigurationStatus : PriorityLevelConfigurationStatus represents the current state of a \"request-priority\".



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta3PriorityLevelConfigurationStatus {
    /// `conditions` is the current state of \"request-priority\".
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::V1beta3PriorityLevelConfigurationCondition>>,
}

impl V1beta3PriorityLevelConfigurationStatus {
    /// PriorityLevelConfigurationStatus represents the current state of a \"request-priority\".
    pub fn new() -> V1beta3PriorityLevelConfigurationStatus {
        V1beta3PriorityLevelConfigurationStatus {
            conditions: None,
        }
    }
}


