/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1ServiceCidrStatus : ServiceCIDRStatus describes the current state of the ServiceCIDR.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1ServiceCidrStatus {
    /// conditions holds an array of metav1.Condition that describe the state of the ServiceCIDR. Current service state
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::V1Condition>>,
}

impl V1beta1ServiceCidrStatus {
    /// ServiceCIDRStatus describes the current state of the ServiceCIDR.
    pub fn new() -> V1beta1ServiceCidrStatus {
        V1beta1ServiceCidrStatus {
            conditions: None,
        }
    }
}


