/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta3ServiceAccountSubject : ServiceAccountSubject holds detailed information for service-account-kind subject.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta3ServiceAccountSubject {
    /// `name` is the name of matching ServiceAccount objects, or \"*\" to match regardless of name. Required.
    #[serde(rename = "name")]
    pub name: String,
    /// `namespace` is the namespace of matching ServiceAccount objects. Required.
    #[serde(rename = "namespace")]
    pub namespace: String,
}

impl V1beta3ServiceAccountSubject {
    /// ServiceAccountSubject holds detailed information for service-account-kind subject.
    pub fn new(name: String, namespace: String) -> V1beta3ServiceAccountSubject {
        V1beta3ServiceAccountSubject {
            name,
            namespace,
        }
    }
}


