/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1ParentReference : ParentReference describes a reference to a parent object.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1ParentReference {
    /// Group is the group of the object being referenced.
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    /// Name is the name of the object being referenced.
    #[serde(rename = "name")]
    pub name: String,
    /// Namespace is the namespace of the object being referenced.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// Resource is the resource of the object being referenced.
    #[serde(rename = "resource")]
    pub resource: String,
}

impl V1beta1ParentReference {
    /// ParentReference describes a reference to a parent object.
    pub fn new(name: String, resource: String) -> V1beta1ParentReference {
        V1beta1ParentReference {
            group: None,
            name,
            namespace: None,
            resource,
        }
    }
}


