/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta3Subject : Subject matches the originator of a request, as identified by the request authentication system. There are three ways of matching an originator; by user, group, or service account.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta3Subject {
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<crate::models::V1beta3GroupSubject>>,
    /// `kind` indicates which one of the other fields is non-empty. Required
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "serviceAccount", skip_serializing_if = "Option::is_none")]
    pub service_account: Option<Box<crate::models::V1beta3ServiceAccountSubject>>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::V1beta3UserSubject>>,
}

impl V1beta3Subject {
    /// Subject matches the originator of a request, as identified by the request authentication system. There are three ways of matching an originator; by user, group, or service account.
    pub fn new(kind: String) -> V1beta3Subject {
        V1beta3Subject {
            group: None,
            kind,
            service_account: None,
            user: None,
        }
    }
}


