/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1ServiceCidrSpec : ServiceCIDRSpec define the CIDRs the user wants to use for allocating ClusterIPs for Services.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1ServiceCidrSpec {
    /// CIDRs defines the IP blocks in CIDR notation (e.g. \"192.168.0.0/24\" or \"2001:db8::/64\") from which to assign service cluster IPs. Max of two CIDRs is allowed, one of each IP family. This field is immutable.
    #[serde(rename = "cidrs", skip_serializing_if = "Option::is_none")]
    pub cidrs: Option<Vec<String>>,
}

impl V1beta1ServiceCidrSpec {
    /// ServiceCIDRSpec define the CIDRs the user wants to use for allocating ClusterIPs for Services.
    pub fn new() -> V1beta1ServiceCidrSpec {
        V1beta1ServiceCidrSpec {
            cidrs: None,
        }
    }
}


