/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V2ExternalMetricStatus : ExternalMetricStatus indicates the current value of a global metric not associated with any Kubernetes object.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V2ExternalMetricStatus {
    #[serde(rename = "current")]
    pub current: Box<crate::models::V2MetricValueStatus>,
    #[serde(rename = "metric")]
    pub metric: Box<crate::models::V2MetricIdentifier>,
}

impl V2ExternalMetricStatus {
    /// ExternalMetricStatus indicates the current value of a global metric not associated with any Kubernetes object.
    pub fn new(current: crate::models::V2MetricValueStatus, metric: crate::models::V2MetricIdentifier) -> V2ExternalMetricStatus {
        V2ExternalMetricStatus {
            current: Box::new(current),
            metric: Box::new(metric),
        }
    }
}


