/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V2ExternalMetricSource : ExternalMetricSource indicates how to scale on a metric not associated with any Kubernetes object (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster).



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V2ExternalMetricSource {
    #[serde(rename = "metric")]
    pub metric: Box<crate::models::V2MetricIdentifier>,
    #[serde(rename = "target")]
    pub target: Box<crate::models::V2MetricTarget>,
}

impl V2ExternalMetricSource {
    /// ExternalMetricSource indicates how to scale on a metric not associated with any Kubernetes object (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster).
    pub fn new(metric: crate::models::V2MetricIdentifier, target: crate::models::V2MetricTarget) -> V2ExternalMetricSource {
        V2ExternalMetricSource {
            metric: Box::new(metric),
            target: Box::new(target),
        }
    }
}


