/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V2HorizontalPodAutoscalerStatus : HorizontalPodAutoscalerStatus describes the current status of a horizontal pod autoscaler.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V2HorizontalPodAutoscalerStatus {
    /// conditions is the set of conditions required for this autoscaler to scale its target, and indicates whether or not those conditions are met.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::V2HorizontalPodAutoscalerCondition>>,
    /// currentMetrics is the last read state of the metrics used by this autoscaler.
    #[serde(rename = "currentMetrics", skip_serializing_if = "Option::is_none")]
    pub current_metrics: Option<Vec<crate::models::V2MetricStatus>>,
    /// currentReplicas is current number of replicas of pods managed by this autoscaler, as last seen by the autoscaler.
    #[serde(rename = "currentReplicas", skip_serializing_if = "Option::is_none")]
    pub current_replicas: Option<i32>,
    /// desiredReplicas is the desired number of replicas of pods managed by this autoscaler, as last calculated by the autoscaler.
    #[serde(rename = "desiredReplicas")]
    pub desired_replicas: i32,
    /// lastScaleTime is the last time the HorizontalPodAutoscaler scaled the number of pods, used by the autoscaler to control how often the number of pods is changed.
    #[serde(rename = "lastScaleTime", skip_serializing_if = "Option::is_none")]
    pub last_scale_time: Option<String>,
    /// observedGeneration is the most recent generation observed by this autoscaler.
    #[serde(rename = "observedGeneration", skip_serializing_if = "Option::is_none")]
    pub observed_generation: Option<i64>,
}

impl V2HorizontalPodAutoscalerStatus {
    /// HorizontalPodAutoscalerStatus describes the current status of a horizontal pod autoscaler.
    pub fn new(desired_replicas: i32) -> V2HorizontalPodAutoscalerStatus {
        V2HorizontalPodAutoscalerStatus {
            conditions: None,
            current_metrics: None,
            current_replicas: None,
            desired_replicas,
            last_scale_time: None,
            observed_generation: None,
        }
    }
}


