/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V2HpaScalingPolicy : HPAScalingPolicy is a single policy which must hold true for a specified past interval.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V2HpaScalingPolicy {
    /// periodSeconds specifies the window of time for which the policy should hold true. PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min).
    #[serde(rename = "periodSeconds")]
    pub period_seconds: i32,
    /// type is used to specify the scaling policy.
    #[serde(rename = "type")]
    pub _type: String,
    /// value contains the amount of change which is permitted by the policy. It must be greater than zero
    #[serde(rename = "value")]
    pub value: i32,
}

impl V2HpaScalingPolicy {
    /// HPAScalingPolicy is a single policy which must hold true for a specified past interval.
    pub fn new(period_seconds: i32, _type: String, value: i32) -> V2HpaScalingPolicy {
        V2HpaScalingPolicy {
            period_seconds,
            _type,
            value,
        }
    }
}


