/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V2HorizontalPodAutoscalerBehavior : HorizontalPodAutoscalerBehavior configures the scaling behavior of the target in both Up and Down directions (scaleUp and scaleDown fields respectively).



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V2HorizontalPodAutoscalerBehavior {
    #[serde(rename = "scaleDown", skip_serializing_if = "Option::is_none")]
    pub scale_down: Option<Box<crate::models::V2HpaScalingRules>>,
    #[serde(rename = "scaleUp", skip_serializing_if = "Option::is_none")]
    pub scale_up: Option<Box<crate::models::V2HpaScalingRules>>,
}

impl V2HorizontalPodAutoscalerBehavior {
    /// HorizontalPodAutoscalerBehavior configures the scaling behavior of the target in both Up and Down directions (scaleUp and scaleDown fields respectively).
    pub fn new() -> V2HorizontalPodAutoscalerBehavior {
        V2HorizontalPodAutoscalerBehavior {
            scale_down: None,
            scale_up: None,
        }
    }
}


