/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V2ObjectMetricSource : ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V2ObjectMetricSource {
    #[serde(rename = "describedObject")]
    pub described_object: Box<crate::models::V2CrossVersionObjectReference>,
    #[serde(rename = "metric")]
    pub metric: Box<crate::models::V2MetricIdentifier>,
    #[serde(rename = "target")]
    pub target: Box<crate::models::V2MetricTarget>,
}

impl V2ObjectMetricSource {
    /// ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
    pub fn new(described_object: crate::models::V2CrossVersionObjectReference, metric: crate::models::V2MetricIdentifier, target: crate::models::V2MetricTarget) -> V2ObjectMetricSource {
        V2ObjectMetricSource {
            described_object: Box::new(described_object),
            metric: Box::new(metric),
            target: Box::new(target),
        }
    }
}


