/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V2ObjectMetricStatus : ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V2ObjectMetricStatus {
    #[serde(rename = "current")]
    pub current: Box<crate::models::V2MetricValueStatus>,
    #[serde(rename = "describedObject")]
    pub described_object: Box<crate::models::V2CrossVersionObjectReference>,
    #[serde(rename = "metric")]
    pub metric: Box<crate::models::V2MetricIdentifier>,
}

impl V2ObjectMetricStatus {
    /// ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
    pub fn new(current: crate::models::V2MetricValueStatus, described_object: crate::models::V2CrossVersionObjectReference, metric: crate::models::V2MetricIdentifier) -> V2ObjectMetricStatus {
        V2ObjectMetricStatus {
            current: Box::new(current),
            described_object: Box::new(described_object),
            metric: Box::new(metric),
        }
    }
}


