/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V2PodsMetricSource : PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V2PodsMetricSource {
    #[serde(rename = "metric")]
    pub metric: Box<crate::models::V2MetricIdentifier>,
    #[serde(rename = "target")]
    pub target: Box<crate::models::V2MetricTarget>,
}

impl V2PodsMetricSource {
    /// PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.
    pub fn new(metric: crate::models::V2MetricIdentifier, target: crate::models::V2MetricTarget) -> V2PodsMetricSource {
        V2PodsMetricSource {
            metric: Box::new(metric),
            target: Box::new(target),
        }
    }
}


