/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.31.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V2ResourceMetricStatus : ResourceMetricStatus indicates the current value of a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V2ResourceMetricStatus {
    #[serde(rename = "current")]
    pub current: Box<crate::models::V2MetricValueStatus>,
    /// name is the name of the resource in question.
    #[serde(rename = "name")]
    pub name: String,
}

impl V2ResourceMetricStatus {
    /// ResourceMetricStatus indicates the current value of a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source.
    pub fn new(current: crate::models::V2MetricValueStatus, name: String) -> V2ResourceMetricStatus {
        V2ResourceMetricStatus {
            current: Box::new(current),
            name,
        }
    }
}


